### ISSUE TITLE
Run  text generation  报错信息如下，请帮忙解决一下

### ISSUE THREAD

**Issue by etchosts** [OpenVINO-dev-contest/ChineseLLM.openvino#6]
--- loading tokenizer ---
Traceback (most recent call last):
  File "D:\AI\ChineseLLM.openvino\generate_ov.py", line 44, in <module>
    ov_model = ChatGLM3Model(model_id, args.device)
  File "D:\AI\ChineseLLM.openvino\chatglm\modeling.py", line 198, in __init__
    ChatGLM2Model.__init__(self, model_path, device)
  File "D:\AI\ChineseLLM.openvino\chatglm\modeling.py", line 25, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(
  File "C:\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 801, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
  File "C:\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\AiInG\.cache\huggingface\modules\transformers_modules\chatglm3_int4_6b\tokenization_chatglm.py", line 109, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "C:\Users\AiInG\.cache\huggingface\modules\transformers_modules\chatglm3_int4_6b\tokenization_chatglm.py", line 17, in __init__
    assert os.path.isfile(model_path), model_path
  File "C:\Python310\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by OpenVINO-dev-contest** [comment]
你填的模型路径有问题:TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by etchosts** [comment]
> 你填的模型路径有问题:TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

谢谢，这个问题我已经解决了，是因为下载模型的时候把分词器模型文件下载漏了。另外请教一个问题，openvino官方提供了NPU的配置，但开发指南里面没有NPU的开发案例，如果想调用NPU进行LLM的处理，该如何弄呢？

**Comment by OpenVINO-dev-contest** [comment]
目前由于NPU不支持动态尺寸的数据输入，所以暂时无法支持LLM

**Comment by etchosts** [comment]
那哪些模型可以支持NPU呢？

**Comment by etchosts** [comment]
> 目前由于NPU不支持动态尺寸的数据输入，所以暂时无法支持LLM

那哪些模型可以支持NPU呢？

**Comment by OpenVINO-dev-contest** [comment]
目前没有一个完整的模型支持列表，不过你可以通过查询你的模型中是否包含NPU不支持的算子，来判断NPU是否支持该模型：
https://github.com/openvinotoolkit/npu_plugin/tree/develop/sw_runtime_kernels/kernels/prebuild/act_shave_bin

**Comment by etchosts** [comment]
谢谢了，我是业余爱好者，第一次听说算子这个概念，怎么查询模型中的算子呢，是看配置文件吗？

**Comment by etchosts** [comment]
> > 谢谢了，我是业余爱好者，第一次听说算子这个概念，怎么查询模型中的算子呢，是看配置文件吗？
> 
> 通过导出的openvino .xml模型文件可以看到模型中包含那些算子，或者可以通过类似Netron这样的模型可视化工具查看。

好的，谢谢大佬
