### ISSUE TITLE
Runtime error occurs when converting qwen to IR

### ISSUE THREAD

**Issue by zhwuwuwu** [OpenVINO-dev-contest/ChineseLLM.openvino#8]
(llmov) PS C:\Users\zihan\Desktop\bigdl\ov\ChineseLLM.openvino> python qwen/export_ir.py
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 8/8 [00:08<00:00,  1.01s/it]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu and disk.
====Exporting IR=====
C:\Users\zihan\.conda\envs\llmov\lib\site-packages\transformers\modeling_utils.py:4225: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py:811: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if batch_size <= 0:
C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py:835: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif kv_seq_len != hidden_states.size()[1]:
C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py:1288: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seqlen > self._seq_len_cached or ntk_alpha != self._ntk_alpha_cached:
C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py:482: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if key_size > self.seq_length and self.use_logn_attn and not self.training:
C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py:502: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if query.size(1) == key_size:
Traceback (most recent call last):
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\frontend\pytorch\ts_decoder.py", line 28, in __init__
    pt_module = self._get_scripted_model(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\frontend\pytorch\ts_decoder.py", line 111, in _get_scripted_model
    scripted = torch.jit.trace(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\jit\_trace.py", line 798, in trace
    return trace_module(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\jit\_trace.py", line 1065, in trace_module
    module._c._create_method_from_trace(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py", line 1043, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py", line 891, in forward
    outputs = block(
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\zihan\.cache\huggingface\modules\transformers_modules\Qwen\Qwen-7B-Chat\93a65d34827a3cc269b727e67004743b723e2f83\modeling_qwen.py", line 608, in forward
    layernorm_output = self.ln_1(hidden_states)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\hooks.py", line 161, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\hooks.py", line 328, in pre_forward
    value = self.weights_map[name]
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\utils\offload.py", line 118, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\accelerate\utils\offload.py", line 171, in __getitem__
    tensor = f.get_tensor(weight_info.get("weight_name", key))
ValueError: could not determine the shape of object type 'torch.storage.UntypedStorage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zihan\Desktop\bigdl\ov\ChineseLLM.openvino\qwen\export_ir.py", line 74, in <module>
    ov_model = ov.convert_model(model, example_input=dummy_inputs)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\tools\ovc\convert.py", line 101, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 534, in _convert
    raise e
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\tools\ovc\convert_impl.py", line 445, in _convert
    get_pytorch_decoder(args['input_model'], example_inputs, args)
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\tools\ovc\moc_frontend\pytorch_frontend_utils.py", line 35, in get_pytorch_decoder
    decoder = TorchScriptPythonDecoder(model, example_input=inputs, shared_memory=args.get("share_weights", True))
  File "C:\Users\zihan\.conda\envs\llmov\lib\site-packages\openvino\frontend\pytorch\ts_decoder.py", line 39, in __init__
    raise RuntimeError(
RuntimeError: Couldn't get TorchScript module by tracing. With exception:
could not determine the shape of object type 'torch.storage.UntypedStorage'
Please check correctness of provided 'example_input'.  You can also provide TorchScript module that you obtained yourself, please refer to PyTorch documentation: https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html.

**Comment by zhwuwuwu** [comment]
Seems to be caised by insufficiency of RAM, trying with WA convert IR on server.

**Comment by OpenVINO-dev-contest** [comment]
Hi @zhwuwuwu the content is this repo is out of date. For QWEN example please refer to this [notebooks](https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/llm-chatbot)
